#### Create polar bar plots
#### From: http://conormclaughlin.net/2018/07/creating-circumplex-polar-bar-charts-in-r-with-ggplot2/
####       http://rstudio-pubs-static.s3.amazonaws.com/72298_c1ba7f77276a4f27a0f375cadc9fac5d.html
#### Enrique Montes
#### October 5, 2019

# Import tidyverse to have access to dplyr and ggplot2
library(tidyverse)

#### FOR THE FKNMS
# Create a data frame with columns "variable" and "value"
data <- data.frame(
  variable = c(
    "Very Oligo. 1",
    "Very Oligo. 2",
    "Very Oligo. 3",
    "Mod. Oligo. 1",
    "Warm Oligo.",
    "Winter Oligo.",
    "Mod. Oligo. 2",
    "Meso. Winter 1", 
    "Meso. Winter 2", 
    "Meso. Summer",
    "Trans. Summer",
    "Trans. Winter",
    "Florida Bay Cool",
    "Florida Bay Warm",
    "Nearshore",
    "Opt. Shallow 1",
    "Opt. Shallow 2",
    "Opt. Shallow 3"
  ), 
  value = sample(18, replace = TRUE))

# Create a simple column chart using the data frame, colored by variable
plot <- ggplot(data,
               aes(
                 x = variable,
                 y = value,
                 fill = factor(variable)
               )) +
  geom_col(width = 1, color = "white") 

# Create bar plot color lookup table
color_tbl = c("#000099", "#0000CC", "#0000FF", "#0033FF", "#0066FF", "#0099FF",
  "#00CCFF", "#00FFFF", "#33FFCC", "#66FF99", "#99FF66", "#CCFF33", "#FFFF00",
  "#FFCC00", "#FF9900", "#FF6600", "#FF3300", "#FF0000")

#### use this code to generate colors:
# red = cmap_rgb$X33[1]
# green = cmap_rgb$X33[2]
# blue = cmap_rgb$X33[3]
# rgb(red,green,blue, maxColorValue = 255)
####
  
# View the plot
plot2 <- plot + coord_polar() + labs(
  x = "",
  y = "",
  title = "Your Title",
  subtitle = "Your Subtitle", 
  caption = "Your Caption"
) + 
  # Assign the ggplot2 minimal theme
  theme_minimal() +
  
  # Remove legend, axes, text, and tick marks
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = element_text(face = "bold", size = 16),
    plot.title = element_text(size = 24, face = "bold"),
    plot.subtitle = element_text(size = 12)
  )

# View the plot
plot2 + scale_fill_manual(values = color_tbl)

# ggsave("YOUR_FILENAME.png", width = 16, height = 12, unit = "in")


################################################################################################################
#### FOR GLOBAL SEASCAPE CLASSES

library(tidyverse)

setwd("~/polar_barplot_seascapes/data/patag") ## change LME

## read data: the csv file is generated by GET_SEASCAPE_v2.m
seascapes = read_csv(file="hist_vals_patag.csv", col_names = FALSE) ## change LME
dates <- c("2018-1", "2018-2", "2018-3", "2018-4", "2018-5", "2018-6", "2018-7", "2018-8", "2018-9", "2018-10", "2018-11", "2018-12")

for(i in 1:nrow(seascapes)) {
  
  sel_date <- dates[i]

# Create a data frame with columns "variable" and "value"
data <- data.frame(
  variable = as.factor(1:33), value = t(seascapes[i,]))

# Create a simple column chart using the data frame, colored by variable
plot <- ggplot(data, aes(variable, value, fill = variable)) +
  geom_bar(width = 1, stat = "identity", color = "white") + 
  scale_y_continuous(breaks = 0:nlevels(data$variable)) +
  theme_gray() +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.line = element_blank())
plot 

# Create bar plot color lookup table
color_tbl = c("#00009F", "#0000BF", "#0000DF", "#0000FF", "#001FFF", "#003FFF", "#005FFF", "#007FFF", "#009FFF",
"#00BFFF", "#00DFFF", "#00FFFF", "#1FFFDF", "#3FFFBF", "#5FFF9F", "#7FFF7F", "#9FFF5F", "#BFFF3F", "#DFFF1F", "#FFFF00",
 "#FFDF00", "#FFBF00", "#FF9F00", "#FF7F00", "#FF5F00", "#FF3F00", "#FF1F00", "#FF0000", "#DF0000", "#BF0000", "#A5A5A5",
 "#B2B2B2", "#D8D8D8")

# View the plot
plot2 <- plot + coord_polar() + labs(
  x = "",
  y = "",
  title = sel_date) + 
  # Assign the ggplot2 minimal theme
  theme_minimal() +
  
  # Remove legend, axes, text, and tick marks
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = element_text(face = "bold", size = 20),
    plot.title = element_text(size = 24, face = "bold"),
    plot.subtitle = element_text(size = 12)
  )

# View the plot
plot3 <- plot2 + scale_fill_manual(values = color_tbl)

filename <- paste("patag", i, ".jpeg") ## change LME

ggsave(plot= plot3, filename = filename, device = "jpeg", width = 10, height = 11,  dpi=300)

}

